### ISSUE TITLE
What is the usage of SpawnStorage ?

### ISSUE THREAD

**Issue by Hendra-Huang** [soverdrive/justonce#1]
I have some questions:

1. I saw there is a function named `SpawnStorage`. What is it for ? If I dive in the code, `SpawnStorage` returns and `Instance` instead of `Storage`.

2. There is struct `Params` which has `KVStorage` property with type `Instance`. What is the purpose of `KVStorage` in `Params` ? Because that `KVStorage` is not passed to `justonceInstance` and `PreventDuringInterval` always using `defaultInstance`. Is it only for validation ?

**Comment by soverdrive** [comment]
Hi,
>1. I saw there is a function named SpawnStorage. What is it for ? If I dive in the code, SpawnStorage returns and Instance instead of Storage.

I prepared `SpawnStorage()` so I can use any `Instance` in different part of code, so anyone who use this will have a freedom to choose single storage for all the system or different one for each action. I actually couldn't decide what is the proper naming for `a data structure that can save a value` here, and I decided to name the interface of it `Storage` and implementation of it called `Instance`.

As far as I know, interface in Go cannot be returned as initialized type, so you have to put a wrapper to say that the function will return data structure that satisfy the interface. Thus it returns `Instance` instead of `Storage`

>2. There is struct Params which has KVStorage property with type Instance. What is the purpose of KVStorage in Params ? Because that KVStorage is not passed to justonceInstance and PreventDuringInterval always using defaultInstance. Is it only for validation ?

`KVStorage` in `Params` is an `Instance` that defined by user when `Init()` or `SpawnStorage()` is called. And **LOL**, I forgot to change the code. Function `PreventDuringInterval()` should use `justonceInstance.KVStorage` instead of `defaultInstance`. Thanks, I will make a pull request to change that

**Comment by soverdrive** [comment]
And it is updated. Thanks @Hendra-Huang. I changes the naming though

**Comment by Hendra-Huang** [comment]
> Function PreventDuringInterval() should use justonceInstance.KVStorage instead of defaultInstance. Thanks, I will make a pull request to change that

Cool

> I decided to name the interface of it Storage and implementation of it called Instance

I still don't get it why you need to return the implementation of `Storage`. For example in [osin](https://github.com/RangelReale/osin/blob/master/storage.go) package. They have the `Storage` interface and they don't provide any implementation of `Storage`, so we can use our own storage. Is this what you want to achieve ?

**Comment by soverdrive** [comment]
wait, you're right. I can initialized variable with interface type. Just realized that. Actually it is better to let it be interface type. I will create one more pr for this.

but I still need the implementation struct of it, to do a validation. or do you have an idea how can I compare between interface?

**Comment by Hendra-Huang** [comment]
> but I still need the implementation struct of it, to do a validation. or do you have an idea how can I compare between interface?

did you mean the comparation in this part of code ?
```
if p.KVStorage == (Instance{}) {
	return ErrNoStorage
}
```
I think you can just make `Params.KVStorage` as an `Storage` type and for validation, just change the code to `if p.KVStorage == nil`.

**Comment by soverdrive** [comment]
really appreciate your suggestion. now it looks much more tidy.

**Comment by Hendra-Huang** [comment]
Cool. I think this issue is resolved. I will close it
